apiVersion: v1
kind: ConfigMap
metadata:
  name: rm-configmap
  namespace: gb4
  labels:
    app: redmine
data:
  PGDATA: /var/lib/postgresql/data/pgdata
  POSTGRES_DB: testdatabase
  POSTGRES_USER: testuser
  REDMINE_DB_POSTGRES: database
  REDMINE_DB_USERNAME: testuser
  REDMINE_DB_DATABASE: testdatabase
  
  