apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pg-persistentvolumeclaim
  namespace: gb4
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: hostpath